### ISSUE TITLE
[BUG] Refactor yolov11 dir

### ISSUE THREAD

**Issue by boyamie** [boostcampaitech7/level2-objectdetection-cv-21#110]
## Describe the bug
- 주말동안 무한 디버깅 지옥에 갇혀있다가 내린 결론입니다.
- out of memory로 서버가 터져서 배치 줄여볼 생각입니다. (16에 터져서 배치사이즈 4로 해볼 생각입니다.)

## To Reproduce
JSON 파일을 사용하지 않고 이미지와 `.txt` 라벨 파일만을 이용하게 된 이유는 다음과 같습니다:

1. **YOLO 학습 구조와 요구사항**
   - YOLO 모델은 학습 시 이미지 파일과 해당 이미지에 대한 라벨 파일(`.txt`)을 필요로 합니다. 라벨 파일은 이미지 파일과 같은 이름을 가지며, YOLO 형식의 바운딩 박스 정보를 포함해야 합니다.
   - `data.yaml` 파일에서 `train`과 `val` 경로는 이미지가 저장된 디렉토리를 가리켜야 하며, 이미지와 같은 이름의 `.txt` 파일이 해당 디렉토리나 하위 디렉토리에 존재해야 합니다.

2. **COCO 형식의 JSON 파일은 YOLO 형식과 다름**
   - COCO 형식의 JSON 파일은 객체 검출 정보를 다른 구조로 저장하며, 이를 바로 YOLO 모델 학습에 사용할 수 없습니다. COCO 형식의 JSON 파일은 객체의 `bbox`, `segmentation`, `category_id` 등 다양한 정보를 포함하지만, YOLO 형식의 `[class_id] [x_center] [y_center] [width] [height]`와는 다릅니다.
   - 따라서 COCO 형식의 JSON 파일을 직접 사용할 경우, 별도의 변환 과정이 필요합니다.

3. **기존 데이터셋의 구조 변경이 어려움**
   - 학습을 위해 이미지를 `train_split`과 `val_split`으로 나눈 후, JSON 파일을 이용한 변환 대신 직접 이미지와 `.txt` 파일을 이용하는 것이 더 간단하고 직관적이었습니다.
   - JSON 파일을 사용하려면, 이를 YOLO 형식의 `.txt` 파일로 변환하는 추가적인 스크립트가 필요하며, 변환 과정에서 오류가 발생할 가능성도 존재했습니다.

4. **라벨 파일 생성 시 자동화 문제**
   - 이미 라벨 파일(`.txt`)이 준비된 상태였기 때문에, JSON 파일을 사용해 다시 라벨을 생성할 필요가 없었습니다. 즉, 이미 분할된 이미지와 라벨을 그대로 사용하는 것이 더 효율적이었습니다.

결론적으로, JSON 파일을 사용하지 않고 직접 이미지와 `.txt` 라벨 파일을 이용하는 방식이 YOLO 학습 구조에 더 적합하고 단순한 방법이었습니다.

## Possible Solution
현재까지 진행된 debugging 과정에서 확인된 문제 없는 정보들을 정리해보면 다음과 같습니다:

1. **데이터 디렉토리 구성**
   - 이미지와 라벨 파일은 각각 `train_split`과 `val_split` 디렉토리에 잘 정리되어 있습니다.
   - 예시 경로:
     - 학습 이미지 및 라벨: `/data/ephemeral/home/dataset/train_split`
     - 검증 이미지 및 라벨: `/data/ephemeral/home/dataset/val_split`

2. **이미지와 라벨 파일 구성**
   - 각 이미지 파일(`.jpg`)과 동일한 이름의 라벨 파일(`.txt`)이 존재합니다. 예를 들어, `0001.jpg`에 대한 라벨은 `0001.txt`로 존재합니다.
   - 라벨 파일은 YOLO 형식의 `[class_id] [x_center] [y_center] [width] [height]` 형식으로 작성되어 있습니다.
   - 라벨 파일은 비어 있지 않으며, 모든 값이 0에서 1 사이의 정규화된 값으로 작성되어 있습니다.

3. **`data.yaml` 설정**
   - `data.yaml` 파일의 경로가 정확히 설정되어 있습니다. 설정 예시는 다음과 같습니다:
     ```yaml
     train: /data/ephemeral/home/dataset/train_split
     val: /data/ephemeral/home/dataset/val_split

     nc: 10  # 클래스 수
     names: ['General trash', 'Paper', 'Paper pack', 'Metal', 'Glass', 'Plastic', 'Styrofoam', 'Plastic bag', 'Battery', 'Clothing']
     ```
   - `nc`는 클래스의 수로, 라벨 파일의 `class_id` 범위와 일치합니다.

4. **YOLO 학습 코드**
   - YOLO 모델 학습 코드는 W&B를 이용하여 정상적으로 초기화되고, 모델도 정상적으로 로드됩니다.
   - `train.py`는 `data.yaml` 파일을 사용하여 이미지와 라벨을 불러오도록 설정되어 있습니다.

## Your Environment
- (3에폭에 서버가 터졌지만) 이와 같은 정보들은 현재 오류가 발생하지 않았으며, 정상적으로 설정된 상태입니다. 학습을 진행하기 위한 기본적인 구성 요소는 문제가 없음을 확인할 수 있습니다.
